=== ALVPI/RepasoSSW/XML_DTD/torneo.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT torneo (partido*)>
<!ELEMENT partido (encuentro, resultado, goles*, arbitro,tarjetas*)>
<!ATTLIST partido
  numero CDATA #REQUIRED
>
<!ELEMENT encuentro (local, visitante)>
<!ELEMENT goles (marcador, goleador, minuto)>
<!ATTLIST goles
      tipo (normal | penalti | propiaPuerta) "normal"
>
<!ELEMENT tarjetas (nombre, minuto)>
<!ATTLIST tarjetas
      tipo (amarilla | roja ) #REQUIRED
>
<!ELEMENT resultado (#PCDATA)>
<!ELEMENT arbitro (#PCDATA)>
<!ELEMENT local (#PCDATA)>
<!ELEMENT visitante (#PCDATA)>
<!ELEMENT marcador (#PCDATA)>
<!ELEMENT goleador (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT minuto (#PCDATA)>

=== ALVPI/RepasoSSW/XML_DTD/torneo.xml
<?xml version="1.0" enconding="UTF-8"?>
<!DOCTYPE torneo SYSTEM "torneo.dtd">
<torneo>
<partido numero="1">
    <encuentro>
      <local>Athletic</local>
      <visitante>Real Madrid</visitante>
    </encuentro>
    <resultado>1-0</resultado>
    <goles>
      <marcador>1-0</marcador>
      <goleador>Aduriz</goleador>
      <minuto>26</minuto>
    </goles>
    <arbitro>Undiano Mallenco</arbitro>
    <tarjetas tipo="amarilla"> 
      <nombre>Kross</nombre>
      <minuto>12</minuto>
    </tarjetas>
    <tarjetas tipo="amarilla">
      <nombre>Aduriz</nombre>
      <minuto>24</minuto>
    </tarjetas>
    <tarjetas tipo="amarilla">
      <nombre>Illaramendi</nombre>
      <minuto>36</minuto>
    </tarjetas tipo="amarilla">
      <nombre>Illaramendi</nombre>
     <minuto>92</minuto>
    </tarjetas>
    <tarjetas>
        <nombre>Isco</nombre>
        <minuto>80</minuto>
    </tarjetas>
   
  </partido>
</torneo>
